<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;

class AppStartupInstall extends Command
{
    protected $signature   = 'app:install-startup {--uninstall : Remove the startup task from Windows Task Scheduler}';
    protected $description = 'Install (or remove) the Windows Task Scheduler entry that auto-starts the queue worker on login';

    public function handle(): int
    {
        if (PHP_OS_FAMILY !== 'Windows') {
            $this->error('This command is Windows-only.');
            $this->line('On Linux/macOS, use a Supervisor config or a systemd service instead.');
            return 1;
        }

        return $this->option('uninstall') ? $this->uninstall() : $this->install();
    }

    // ─── Helpers ──────────────────────────────────────────────────────────────

    /** Windows Startup folder — no admin rights needed; runs on every user login. */
    private function startupFolder(): string
    {
        return getenv('APPDATA') . '\\Microsoft\\Windows\\Start Menu\\Programs\\Startup';
    }

    private function launcherPath(): string
    {
        return $this->startupFolder() . '\\alcat-queue-worker.bat';
    }

    private function ps1Path(): string
    {
        return base_path('start-queue.ps1');
    }

    // ─── Install ─────────────────────────────────────────────────────────────

    private function install(): int
    {
        $base = base_path();
        $php  = PHP_BINARY;
        $ps1  = $this->ps1Path();
        $bat  = $this->launcherPath();

        // 1. Write the PowerShell worker script (paths baked-in for this machine).
        $this->writePs1($ps1, $php, $base);
        $this->line("  Worker script   → {$ps1}");

        // 2. Write a tiny .bat launcher into the Windows Startup folder.
        //    No admin rights needed; runs silently when this user logs in.
        $this->writeBat($bat, $ps1);
        $this->line("  Startup entry   → {$bat}");

        $this->newLine();
        $this->info('Done! The queue worker will start automatically on your next Windows login.');
        $this->newLine();
        $this->comment('To start it right now without rebooting:');
        $this->line('  php artisan queue:work --tries=5');
        $this->newLine();
        $this->comment('To remove the auto-start later:');
        $this->line('  php artisan app:install-startup --uninstall');

        return 0;
    }

    private function writePs1(string $path, string $php, string $base): void
    {
        $content  = "# Alcat-system – Queue Worker\n";
        $content .= "# Generated by: php artisan app:install-startup\n\n";
        $content .= "Start-Sleep -Seconds 30   # wait for Laragon / MySQL to finish starting\n\n";
        $content .= "Start-Process \"{$php}\" `\n";
        $content .= "    -ArgumentList \"artisan\", \"queue:work\", \"--tries=5\", \"--timeout=90\" `\n";
        $content .= "    -WorkingDirectory \"{$base}\" `\n";
        $content .= "    -WindowStyle Hidden\n";

        file_put_contents($path, $content);
    }

    private function writeBat(string $path, string $ps1): void
    {
        // The BAT file is what Windows Startup folder actually executes.
        // It launches PowerShell invisibly so no window flashes on login.
        $content  = "@echo off\n";
        $content .= "powershell.exe -WindowStyle Hidden -NonInteractive -ExecutionPolicy Bypass -File \"{$ps1}\"\n";

        file_put_contents($path, $content);
    }

    // ─── Uninstall ────────────────────────────────────────────────────────────

    private function uninstall(): int
    {
        $removed = false;

        $bat = $this->launcherPath();
        if (file_exists($bat)) {
            unlink($bat);
            $this->info("Startup entry removed → {$bat}");
            $removed = true;
        }

        $ps1 = $this->ps1Path();
        if (file_exists($ps1)) {
            unlink($ps1);
            $this->line("Worker script removed → {$ps1}");
            $removed = true;
        }

        if (! $removed) {
            $this->warn('Nothing to remove — the startup entry was not installed.');
        }

        return 0;
    }
}
