# Alcat-system – Queue Worker Startup Script
# Generated by: php artisan app:install-startup
# To regenerate, re-run the artisan command.

Start-Sleep -Seconds 30   # give Windows services time to finish starting

Start-Process "C:\laragon\bin\php\php-8.3.29-Win32-vs16-x64\php.exe" `
    -ArgumentList "artisan", "queue:work", "--tries=5", "--timeout=90" `
    -WorkingDirectory "C:\laragon\www\Alcat-system" `
    -WindowStyle Hidden
